# nixpacks.toml (vers√£o corrigida 2)

[phases.setup]
cmds = [
  "apt-get update",
  "apt-get install -y --no-install-recommends libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libasound2t64 libpangocairo-1.0-0 libxshmfence1 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libx11-xcb1 libxtst6 libdrm2 libxkbcommon0 lsb-release"
]