name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ] # O deploy roda sempre que houver push na branch main

jobs:
  # ==========================================
  # 1. FASE DE SOURCE
  # ==========================================
  source:
    name: Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validar Source
        run: echo "Código carregado com sucesso! Pronto para a build."

  # ==========================================
  # 2. FASE DE BUILD
  # ==========================================
  build:
    name: Build & Push
    needs: source # Só avança se a fase 'source' tiver sucesso
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  # ==========================================
  # 3. FASE DE DEPLOY
  # ==========================================
  deploy:
    name: Deploy to EC2
    needs: build # Só avança se a fase 'build' tiver sucesso
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          ECR_REGISTRY: ${{ needs.build.outputs.registry }} 
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          IMAGE_TAG: latest
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: ECR_REGISTRY,ECR_REPOSITORY,AWS_REGION,IMAGE_TAG 
          script: |
            # Fazer login no ECR dentro da EC2 para conseguir baixar a imagem
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
            
            # Entrar na pasta do projeto
            cd ~/bot-fut-app
            
            # Baixar a nova imagem e reiniciar o container
            docker-compose down
            docker-compose pull
            docker-compose up -d